org.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g
org.gradle.caching=true
kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true
# 打 Windows 安装包要带 jpackage 的完整 JDK（Android Studio 自带的 jbr 没有 jpackage）
packageJdk=F:/JDK
