[versions]
kotlin = "2.4.0"
agp = "9.2.1"
cmp = "1.12.1"
cmp-material3 = "1.12.0-alpha03"
coroutines = "1.11.0"
serialization = "1.11.0"
ktor = "3.5.0"
pdfbox = "3.0.8"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
cmp-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "cmp" }
cmp-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "cmp" }
cmp-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "cmp" }
cmp-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "cmp-material3" }
cmp-icons = { module = "org.jetbrains.compose.material:material-icons-extended", version = "1.7.3" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }
androidx-activity-compose = "androidx.activity:activity-compose:1.13.0"
androidx-core-ktx = "androidx.core:core-ktx:1.19.0"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "cmp" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
